# Generated by Django 4.2.10 on 2024-03-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
    ]
