# Generated by Django 4.2.10 on 2024-05-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_options_alter_postcategory_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Thread',
        ),
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='ThreadCategory',
        ),
    ]
