# Generated by Django 4.2.10 on 2024-05-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='short_bio',
        ),
    ]
