# Generated by Django 4.2.10 on 2024-05-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_profile_short_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='display_name',
        ),
    ]
