# Generated by Django 5.0.2 on 2024-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_management', '0002_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='profile_set', related_query_name='profile', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='profile_perm_set', related_query_name='profile', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
