# Generated by Django 4.2.10 on 2024-05-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
    ]
